import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'

import {
  MAX_PAID_MEDIA_ASSET_BYTES,
  PAID_MEDIA_ASSET_ACK_SCHEMA,
  PAID_MEDIA_ASSET_RESULT_SCHEMA,
  PaidMediaAssetProtocolError,
  buildPaidMediaAssetAck,
  canonicalPaidMediaAssetResult,
  paidMediaAssetResultDigest,
  paidMediaAssetTokenHash,
  paidMediaTokenSetDigest,
  parsePaidMediaAssetAck,
  parsePaidMediaAssetResult
} from './paid-media-asset-protocol'

const token = (character: string): string => `nma1_${character.repeat(43)}`
const digest = (label: string): string => createHash('sha256').update(label).digest('hex')

function result() {
  return {
    schema: PAID_MEDIA_ASSET_RESULT_SCHEMA,
    kind: 'image',
    created: 1784200000,
    turnId: digest('turn'),
    assets: [
      {
        token: token('A'),
        mediaType: 'image/png',
        byteLength: 123456,
        sha256: digest('asset'),
        validationReceiptSha256: digest('validation')
      }
    ]
  }
}

describe('paid media asset protocol v2', () => {
  it('parses a closed bounded result and emits deterministic canonical JSON', () => {
    const parsed = parsePaidMediaAssetResult(result())
    expect(parsed.assets).toHaveLength(1)
    expect(JSON.parse(canonicalPaidMediaAssetResult(parsed).toString('ascii'))).toEqual(result())
    expect(paidMediaAssetResultDigest(parsed)).toMatch(/^[0-9a-f]{64}$/)
    expect(paidMediaAssetResultDigest(parsed)).toBe(paidMediaAssetResultDigest(result()))
    // Cross-runtime fixture generated by the Gateway implementation.  This
    // catches harmless-looking object-order changes that would fork receipts.
    expect(paidMediaAssetResultDigest(parsed)).toBe(
      'b12ba7445e0930220257c4489d8a204a28b72322473a13eb0fb8c8c4269dd315'
    )
    expect(() =>
      canonicalPaidMediaAssetResult(Object.freeze({ ...result(), providerUrl: 'https://invalid' }))
    ).toThrow(PaidMediaAssetProtocolError)
  })

  it('rejects provider URLs, oversized assets, duplicate tokens, and cross-kind bytes', () => {
    expect(() => parsePaidMediaAssetResult({ ...result(), providerUrl: 'https://invalid' })).toThrow(
      PaidMediaAssetProtocolError
    )
    const oversized = result()
    oversized.assets[0].byteLength = MAX_PAID_MEDIA_ASSET_BYTES + 1
    expect(() => parsePaidMediaAssetResult(oversized)).toThrow(PaidMediaAssetProtocolError)
    const duplicated = result()
    duplicated.assets.push({ ...duplicated.assets[0] })
    expect(() => parsePaidMediaAssetResult(duplicated)).toThrow(/duplicated/i)
    expect(() => parsePaidMediaAssetResult({ ...result(), kind: 'video' })).toThrow(
      PaidMediaAssetProtocolError
    )
  })

  it('hashes tokens in a separate domain and canonicalizes token sets', () => {
    expect(paidMediaAssetTokenHash(token('A'))).not.toContain(token('A'))
    expect(paidMediaTokenSetDigest([token('A'), token('B')])).toBe(
      paidMediaTokenSetDigest([token('B'), token('A')])
    )
    expect(paidMediaTokenSetDigest([token('A'), token('B')])).toBe(
      '7f801257d1e90a3d4292ca552375b225d42c1042a1a090b54567b99ee2e9d0b0'
    )
    expect(() => paidMediaTokenSetDigest([token('A'), token('A')])).toThrow(/token set/i)
  })

  it('builds and strictly parses a full-set archive ACK', () => {
    const value = buildPaidMediaAssetAck(result(), digest('archive'))
    expect(value).toEqual({
      schema: PAID_MEDIA_ASSET_ACK_SCHEMA,
      turnId: digest('turn'),
      tokens: [token('A')],
      archiveReceiptSha256: digest('archive')
    })
    expect(parsePaidMediaAssetAck(value)).toEqual(value)
    expect(() => parsePaidMediaAssetAck({ ...value, extra: true })).toThrow(
      PaidMediaAssetProtocolError
    )
  })
})
